# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    images_directory: '%kernel.root_dir%/../web/images'

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    
    app.file_uploader:
        class: DiyohBundle\Service\FileUploader
        arguments: ['%images_directory%']
    fos_user.change_password.edit.success:
        class: DiyohBundle\EventListener\RedirectAfterPasswordChange
        arguments: ['routing.loader']
    fos_user.registration.completed:
        class: DiyohBundle\EventListener\RedirectAfterRegistration
        arguments: ['routing.loader']