<?php

namespace DiyohBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DiscussionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscussionRepository extends EntityRepository
{
}
