<?php

namespace DiyohBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoiceRepository extends EntityRepository
{
}
